language: node_js

node_js:
  - "stable"

sudo: false

cache: yarn

script:
  - yarn run test:ci

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3

before_deploy:
  - yarn run build
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: react-redux-more.surge.sh
  skip_cleanup: true
